import OpenAI, { toFile } from 'openai';
import { createError } from '../middleware/errorHandler';
import sharp from 'sharp';

export interface EditRequest {
  imageBase64: string;
  prompt: string;
  maskBase64?: string;
}

export interface EditResponse {
  editedImageUrl: string;
  requestId: string;
}

// Lazy initialization of OpenAI client
let openai: OpenAI | null = null;

const getOpenAIClient = (): OpenAI => {
  if (!process.env.OPENAI_API_KEY) {
    throw createError('OpenAI API key not configured', 500);
  }
  
  if (!openai) {
    openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
  }
  
  return openai;
};

const MAX_IMAGE_BYTES = 4 * 1024 * 1024;

async function makeSquarePngUnderLimit(buffer: Buffer, isMask = false): Promise<Buffer> {
  const targetSizes = [1024, 896, 768];

  for (const size of targetSizes) {
    const output = await sharp(buffer, { failOn: 'none' })
      .rotate()
      .resize(size, size, {
        fit: 'contain',
        background: isMask
          ? { r: 0, g: 0, b: 0, alpha: 0 }
          : { r: 255, g: 255, b: 255, alpha: 1 },
      })
      .ensureAlpha()
      .png({
        compressionLevel: 9,
        effort: 10,
        palette: true,
      })
      .toBuffer();

    if (output.length <= MAX_IMAGE_BYTES) {
      return output;
    }
  }

  throw createError('Image too large. Please use an image smaller than 4MB.', 400);
}

export const editImage = async (request: EditRequest): Promise<EditResponse> => {
  const client = getOpenAIClient();
  const preferredModel = process.env.OPENAI_IMAGE_MODEL || 'gpt-image-1';

  const requestId = `edit_${Date.now()}_${Math.random().toString(36).substring(2, 11)}`;

  try {
    console.log(`[${requestId}] Starting image edit request`);

    // Convert base64 to buffer
    const inputImageBuffer = Buffer.from(request.imageBase64.replace(/^data:image\/[a-z]+;base64,/, ''), 'base64');
    const imageBuffer = await makeSquarePngUnderLimit(inputImageBuffer);
    
    // Validate image size (OpenAI requires images to be less than 4MB)
    if (imageBuffer.length > MAX_IMAGE_BYTES) {
      throw createError('Image too large. Please use an image smaller than 4MB.', 400);
    }

    const imageMimeType = 'image/png';
    const imageExt = 'png';
    const maskBuffer = request.maskBase64
      ? await makeSquarePngUnderLimit(
          Buffer.from(request.maskBase64.replace(/^data:image\/[a-z]+;base64,/, ''), 'base64'),
          true
        )
      : undefined;

    console.log(`[${requestId}] Image size: ${(imageBuffer.length / 1024).toFixed(2)}KB`);
    console.log(`[${requestId}] Prompt: ${request.prompt.substring(0, 100)}...`);

    const runEdit = async (model: string) => {
      const imageFile = await toFile(imageBuffer, `input.${imageExt}`, { type: imageMimeType });
      const maskFile = maskBuffer
        ? await toFile(maskBuffer, 'mask.png', { type: 'image/png' })
        : undefined;

      return client.images.edit({
        model,
        image: imageFile,
        mask: maskFile,
        prompt: request.prompt,
        n: 1,
        size: "1024x1024",
        response_format: model === 'dall-e-2' ? 'url' : 'b64_json'
      });
    };

    let response;
    let selectedModel = preferredModel;
    try {
      response = await runEdit(selectedModel);
    } catch (error: any) {
      const message = String(error?.message || '');
      const shouldFallbackToDalle2 =
        selectedModel !== 'dall-e-2' &&
        error?.status === 400 &&
        message.includes('Value must be \'dall-e-2\'');

      if (!shouldFallbackToDalle2) {
        throw error;
      }

      console.warn(`[${requestId}] Model ${selectedModel} rejected, retrying with dall-e-2`);
      selectedModel = 'dall-e-2';
      response = await runEdit(selectedModel);
    }

    if (!response.data || response.data.length === 0) {
      throw createError('No image generated by OpenAI', 500);
    }

    const imageData = response.data[0];
    const editedImageUrl =
      imageData.url ||
      (imageData.b64_json ? `data:image/png;base64,${imageData.b64_json}` : undefined);
    
    if (!editedImageUrl) {
      throw createError('Invalid response from OpenAI', 500);
    }

    console.log(`[${requestId}] Image edit completed successfully with model ${selectedModel}`);
    
    return {
      editedImageUrl,
      requestId
    };

  } catch (error: any) {
    console.error(`[${requestId}] OpenAI API error:`, error);

    // Handle specific OpenAI errors
    if (error.status === 400) {
      throw createError(
        error.message || 'Invalid image or prompt. Please check your input and try again.',
        400
      );
    } else if (error.status === 429) {
      throw createError(
        'API rate limit exceeded. Please try again later.',
        429
      );
    } else if (error.status === 500) {
      throw createError(
        'OpenAI service temporarily unavailable. Please try again later.',
        503
      );
    }

    // Generic error
    throw createError(
      error.message || 'Failed to process image edit',
      500
    );
  }
};

export const validateImageFormat = (base64Image: string): boolean => {
  const imageFormatRegex = /^data:image\/(png|jpeg|jpg|webp);base64,/;
  return imageFormatRegex.test(base64Image);
};

export const detectImageType = (_imageUri: string): 'selfie' | 'full-body' | 'unknown' => {
  // This is a simple heuristic - in a real app you might use computer vision
  // For now, we'll return 'unknown' and let the user specify or use ML models
  return 'unknown';
};